version: "3.7"

services:     
    web:
        # buildはせず、存在するdocker imageを利用するよう指定
        image: yakitori99/classify-animals:v1.8.1
        ports:
            # web server
            - 5000:80
            # ssh
            - 2222:2222
        # ホストOSの起動時、コンテナの不慮の停止時などにコンテナを自動起動するよう指定
        restart: always